package rules;

import com.project.farmeasyportal.entities.LoanForm;
import com.project.farmeasyportal.entities.Apply;
import com.project.farmeasyportal.enums.Status;
import com.project.farmeasyportal.entities.EvaluationRequest;

rule "Reject if Amount is Less Than 70000"
salience 10
when
    $evaluationRequest : EvaluationRequest(amount < 70000)
    $apply : Apply()
then
    $apply.setStatus(Status.REJECTED);
    System.out.println("Rule Matched: amount < 70000 -> Rejected");
end
