spring:
  application:
    name: FarmeasyPortal

  datasource:
    url: jdbc:mariadb://localhost:3308/farmeasy-app?createDatabaseIfNotExist=true
    username: root
    password: mariadb12345
    driver-class-name: org.mariadb.jdbc.Driver
    # Uncomment the following line if needed
    # jpa:
    #   hibernate:
    #     ddl-auto: update

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/farmer/

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
