package rules;

import com.project.farmeasyportal.entities.LoanForm;
import com.project.farmeasyportal.entities.Apply;
import com.project.farmeasyportal.enums.Status;
import com.project.farmeasyportal.entities.EvaluationRequest;

rule "Approve if Amount is More Than 80000"
salience 5
when
    $evaluationRequest : EvaluationRequest(amount >= 80000)
    $apply : Apply()
then
    if ($apply.getStatus() == null || !$apply.getStatus().equals(Status.REJECTED)) {
        $apply.setStatus(Status.PENDING);
    }
    System.out.println("Rule Matched: amount > 80000 -> PENDING");
end
