package rules;

import com.project.farmeasyportal.entities.LoanForm;
import com.project.farmeasyportal.entities.Apply;
import com.project.farmeasyportal.enums.Status;
import com.project.farmeasyportal.entities.EvaluationRequest;

rule "Reject if Cibil is Less Than 800"
salience 10
when
    $evaluationRequest : EvaluationRequest(cibilScore < 800)
    $apply : Apply()
then
    $apply.setStatus(Status.REJECTED);
    System.out.println("Rule Matched: cibilScore <= 800 -> Rejected");
end
