CREATE TABLE FARMER (
    USER_ID     varchar(255) PRIMARY KEY,
    NAME        VARCHAR(20),
    CONTACT     VARCHAR(10),
    EMAIL       VARCHAR(50) UNIQUE,
    PASSWORD    VARCHAR(255),
    ADDRESS     VARCHAR(255)
) ENGINE=InnoDB;
