CREATE TABLE FARMER (
    USER_ID     varchar(255) PRIMARY KEY,
    FIRST_NAME  VARCHAR(255),
    LAST_NAME   VARCHAR(255),
    CONTACT     VARCHAR(20),
    EMAIL       VARCHAR(255) UNIQUE,
    PASSWORD    VARCHAR(255)
) ENGINE=InnoDB;
