CREATE TABLE FARMER (
    USER_ID     varchar(255) PRIMARY KEY,
    FIRST_NAME  VARCHAR(20),
    LAST_NAME   VARCHAR(20),
    CONTACT     VARCHAR(10),
    EMAIL       VARCHAR(30) UNIQUE,
    PASSWORD    VARCHAR(255)
) ENGINE=InnoDB;
