CREATE TABLE Loan_Form (
    id                 INT AUTO_INCREMENT PRIMARY KEY,
    name               VARCHAR(40),
    email              VARCHAR(20),
    contact            VARCHAR(10),
    gender             VARCHAR(10),
    age                int NOT NULL,
    private            int NOT NULL,
    address            VARCHAR(500),
    district           VARCHAR(30),
    state              VARCHAR(20),
    pin_code           VARCHAR(6),
    aadhaar_number     DECIMAL(16),
    aadhaar_pdf_name   VARCHAR(255),
    pan_number         DECIMAL(10),
    pan_pdf_name       VARCHAR(255),
    salary             DECIMAL(10, 2),

    collateral_type    VARCHAR(50),
    guarantor_name     VARCHAR(40),
    guarantor_contact  VARCHAR(10),
    guarantor_relation VARCHAR(30),

    land_amount        VARCHAR(100),
    khsra_number       VARCHAR(20),
    land_ownership     VARCHAR(30),
    soil_type          VARCHAR(20),
    crop_type          VARCHAR(20),
    land_details_pdf   VARCHAR(255)
) ENGINE=InnoDB;
